{
 "title": "Aztec Validator",
 "description": "A Grafana dashboard to monitor an Aztec Validator node",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "data_source", "query": "prometheus" },
   { "name": "selector", "query": "${VAR_SELECTOR}" }
  ]
 },
 "panels": [
  { "title": "Aztec status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(process_cpu_utilization{process_cpu_state=\"user\",$selector}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory use",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_memory_usage{$selector}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk use",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aztec_db_used_size_bytes{$selector}) + sum (aztec_world_state_db_used_size{$selector})",
     "legendFormat": "{{aztec_db_type}}"
    }
   ]
  },
  {
   "title": "P2P traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg (rate(gossipsub_rpc_recv_bytes_total{$selector}[$__rate_interval]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "avg (rate(gossipsub_rpc_sent_bytes_total{$selector}[$__rate_interval]))",
     "legendFormat": "Send"
    }
   ]
  },
  {
   "title": "Current Block Heights",
   "type": "stat",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (aztec_status) (label_replace(aztec_archiver_block_height{$selector,aztec_status=\"\"}, \"aztec_status\", \"Pending chain\", \"aztec_status\", \"^$\"))",
     "legendFormat": "{{aztec_status}}"
    },
    {
     "expr": "max by (aztec_status) (label_replace(aztec_archiver_block_height{$selector,aztec_status=\"proven\"}, \"aztec_status\", \"Proven chain\", \"aztec_status\", \"^proven$\"))",
     "legendFormat": "{{aztec_status}}"
    },
    {
     "expr": "max(aztec_archiver_block_height{ $selector, aztec_status=\"\"}) - max(aztec_archiver_block_height{ $selector ,aztec_status=\"proven\"})",
     "legendFormat": "Pending chain depth"
    },
    {
     "expr": "max(aztec_archiver_prune_count{$selector})",
     "legendFormat": "Re-orgs"
    },
    {
     "expr": "max by (aztec_status) (label_replace(aztec_archiver_l1_block_height{$selector}, \"aztec_status\", \"l1\", \"aztec_status\", \"^$\"))",
     "legendFormat": "L1"
    }
   ]
  },
  {
   "title": "ETH balance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Eth" } },
   "targets": [
    {
     "expr": "avg by (aztec_address_sender,service_name) (aztec_l1_publisher_balance_eth{$selector})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETH consumed last 24h",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "-sum(delta(aztec_l1_publisher_balance_eth{$selector}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recent proposals",
   "type": "gauge",
   "description": "Will show incomplete data if uptime is less than 24h",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "blocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(aztec_sequencer_block_count{$selector,aztec_status=\"built\"}[24h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "floor(delta(aztec_archiver_block_height{$selector, aztec_status=\"\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proposals status in last 24h",
   "type": "piechart",
   "description": "The status of proposals made by this validator",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "blocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (aztec_status) (delta(aztec_sequencer_block_count{$selector}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Block production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Proposals made by this validator",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "blocks" } },
   "targets": [
    {
     "expr": "delta(aztec_sequencer_block_count{$selector,aztec_status=\"built\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "delta(aztec_sequencer_block_count{$selector,aztec_status=\"failed\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "delta(aztec_sequencer_block_count{$selector,aztec_status=\"cancelled\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVG blob tx inclusion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "blocks" } },
   "targets": [
    {
     "expr": "rate(aztec_l1_publisher_blob_inclusion_blocks_sum{$selector}[$__rate_interval])/rate(aztec_l1_publisher_blob_inclusion_blocks_count{$selector}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions per block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "txs" } },
   "targets": [
    {
     "expr": "aztec_sequencer_current_block_size{$selector}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mana consumption rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "mana/s" } },
   "targets": [
    {
     "expr": "aztec_sequencer_block_build_mana_per_second{$selector}",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Block Build Duration",
   "type": "heatmap",
   "description": "Count of blocks that fall within each bucket",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(increase(aztec_sequencer_block_build_duration_milliseconds_bucket{$selector}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Time to collect attestations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(aztec_sequencer_time_to_collect_attestations{$selector}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aztec TPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (rate(aztec_archiver_tx_count{$selector}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "World state", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "World state block heights",
   "type": "stat",
   "description": "The trees maintain a rolling window of snapshots. This panel shows the inteval of blocks we can answer queries for.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aztec_world_state_unfinalised_height{$selector})",
     "legendFormat": "Unfinalized block height"
    },
    {
     "expr": "max(aztec_world_state_finalised_height{$selector})",
     "legendFormat": "Finalized block height"
    },
    {
     "expr": "max(aztec_world_state_oldest_block{$selector})",
     "legendFormat": "Oldest snapshot"
    }
   ]
  },
  {
   "title": "Trees on disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(aztec_merkle_tree_name) (aztec_world_state_db_used_size{$selector})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tree sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "leaves" } },
   "targets": [
    {
     "expr": "sort_desc(max by (aztec_merkle_tree_name) (aztec_world_state_tree_size{$selector}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mempool status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receive TPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 73 },
     "targets": [
      {
       "expr": "rate(aztec_node_receive_tx_count{$selector}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total received txs",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 73 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aztec_node_receive_tx_count{aztec_ok=\"true\", $selector}) or vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total rejected txs",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 73 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aztec_node_receive_tx_count{aztec_ok=\"false\", $selector}) or vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tx mempool status",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(aztec_status) (aztec_mempool_tx_count{$selector})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Attestations in mempool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "attestations" } },
     "targets": [
      {
       "expr": "avg_over_time(aztec_mempool_attestations_count{$selector}[$__interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Synch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Block Sync Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(aztec_archiver_sync_duration_milliseconds_bucket{$selector}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(aztec_archiver_sync_duration_milliseconds_bucket{$selector}[$__rate_interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "World state synch time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(aztec_world_state_request_time_microseconds_bucket{$selector,aztec_world_state_request=\"SYNC_BLOCK\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(aztec_world_state_request_time_microseconds_bucket{$selector,aztec_world_state_request=\"SYNC_BLOCK\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Block height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "avg by(aztec_status) (label_replace(aztec_archiver_block_height{$selector}, \"aztec_status\", \"pending\", \"aztec_status\", \"^$\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mined TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(rate(aztec_archiver_tx_count{$selector}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(service_name, process_cpu_state) (process_cpu_utilization{$selector,process_cpu_state=\"user\"})",
     "legendFormat": "{{service_name}} - {{process_cpu_state}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(service_name) (process_memory_usage{$selector})",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Database size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(aztec_db_used_size_bytes{$selector})",
     "legendFormat": "{{aztec_db_type}}"
    },
    {
     "expr": "sum (aztec_world_state_db_used_size{$selector})",
     "legendFormat": "world-state"
    }
   ]
  },
  {
   "title": "P2P traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_rpc_recv_bytes_total{$selector}[$__rate_interval])*8",
     "legendFormat": "Receive"
    },
    {
     "expr": "rate(gossipsub_rpc_sent_bytes_total{$selector}[$__rate_interval])*8",
     "legendFormat": "Send"
    }
   ]
  }
 ]
}