{
 "title": "Lido Exporter Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Node Operator Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Operator ID",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "csm_node_operator_id" }
   ]
  },
  { "title": "Keys and Bonds Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Keys Information",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "csm_keys_stuck_validators_count",
     "legendFormat": "Stuck Validators"
    },
    {
     "expr": "csm_keys_refunded_validators_count",
     "legendFormat": "Refunded Validators"
    },
    {
     "expr": "csm_keys_exited_validators_count",
     "legendFormat": "Exited Validators"
    },
    {
     "expr": "csm_keys_deposited_validators_count",
     "legendFormat": "Deposited Validators"
    },
    {
     "expr": "csm_keys_depositable_validators_count",
     "legendFormat": "Depositable Validators"
    }
   ]
  },
  {
   "title": "Bonds Information",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "eth" } },
   "targets": [
    { "expr": "csm_bond_current / 1e18", "legendFormat": "Current Bond" },
    { "expr": "csm_bond_required / 1e18", "legendFormat": "Required Bond" },
    { "expr": "csm_bond_excess / 1e18", "legendFormat": "Excess Bond" },
    { "expr": "csm_bond_missed / 1e18", "legendFormat": "Missed Bond" }
   ]
  },
  { "title": "Rewards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Non-Claimed Rewards",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "eth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "csm_non_claimed_rewards / 1e18" }
   ]
  },
  { "title": "Penalties and Exit Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Penalties",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    { "expr": "csm_onchain_penalties_total", "legendFormat": "Penalties" }
   ]
  },
  {
   "title": "Exit Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "csm_onchain_exit_requests_total",
     "legendFormat": "Exit Requests"
    }
   ]
  }
 ]
}