{
 "title": "Global AVS Specification Metrics",
 "description": "Global AVS Specification Metrics for each instance",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Performance Score",
   "type": "gauge",
   "description": "The performance metric is a score between 0 and 100 and each developer can define their own way of calculating the score. The score is calculated based on the performance of the Node and the performance of the backing services.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sedge_performance_score", "legendFormat": "{{instanceID}}" }
   ]
  },
  { "title": "RPC Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "description": "Average Response Time per method in seconds over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(sedge_rpc_request_duration_seconds_sum{method=~\".*\"}[5m])",
     "legendFormat": "{{instanceID}} -> {{method}}"
    }
   ]
  },
  {
   "title": "Total RPC Requests",
   "type": "timeseries",
   "description": "Total of JSON-RPC requests per method.",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 11 },
   "targets": [
    { "expr": "sedge_rpc_request_total", "legendFormat": "${{token}} -> {{instanceID}}" }
   ]
  },
  {
   "title": "Request duration distribution",
   "type": "histogram",
   "description": "Request duration distribution in seconds per method.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(sedge_rpc_request_duration_seconds_count[$__rate_interval])",
     "legendFormat": "{{instanceID}} -> {{method}}"
    }
   ]
  }
 ]
}