{
 "title": "AVS Specification Metrics",
 "description": "AVS Specification Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "InstanceID", "label": "Instance ID", "query": { "query": "label_values(instance_id)" } }
  ]
 },
 "panels": [
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "AVS Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sedge_performance_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Performance Score",
   "type": "gauge",
   "description": "The performance metric is a score between 0 and 100 and each developer can define their own way of calculating the score. The score is calculated based on the performance of the Node and the performance of the backing services.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sedge_performance_score{instanceID=\"$InstanceID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVS Commit Hash (12 first characters)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sedge_performance_score, \"short_commit_hash\", \"$1\", \"instance_commit_hash\", \"(.{12}).*\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sedge_performance_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AVS Node Specification Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sedge_performance_score", "legendFormat": "__auto" }
   ]
  },
  { "title": "Economics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Balance Total",
   "type": "stat",
   "description": "The total balance in AVS Node per used token.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sedge_balance_total{instanceID=\"$InstanceID\"}",
     "legendFormat": "${{token}}"
    }
   ]
  },
  {
   "title": "Slashing incurred",
   "type": "stat",
   "description": "The total slashing incurred per token.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sedge_slashing_incurred_total{instanceID=\"$InstanceID\"}",
     "legendFormat": "${{token}}"
    }
   ]
  },
  {
   "title": "Fees Earned",
   "type": "stat",
   "description": "The total fees earned per token.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sedge_fees_earned_total{instanceID=\"$InstanceID\"}",
     "legendFormat": "${{token}}"
    }
   ]
  },
  { "title": "RPC Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "description": "Average Response Time per method in seconds over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(sedge_rpc_request_duration_seconds_sum{method=~\".*\", instanceID=\"$InstanceID\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total RPC Requests",
   "type": "timeseries",
   "description": "Total of JSON-RPC requests per method.",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sedge_rpc_request_total{instanceID=\"$InstanceID\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Request duration distribution",
   "type": "histogram",
   "description": "Request duration distribution in seconds per method.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(sedge_rpc_request_duration_seconds_count{instanceID=\"$InstanceID\"}[$__rate_interval])",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}